number = { ASCII_DIGIT }
comment = _{ ("#" | " --") ~ (!NEWLINE ~ ANY)* }

password = @{ number{1, 8} }
card = { password ~ " " ~ number }

day = @{ number{2} }
month = @{ number{2} }
year = @ { number{4} }
date = {
    (day ~ "." ~ month ~ "." ~ year) |
    (year ~ "." ~ month)
}

banlist = {
    "!" ~ ((date ~ " TCG") | ("TCG " ~ date)) ~
    (NEWLINE ~ !"!" ~ ((card ~ comment?) | comment | NEWLINE))+
}

conf = { SOI ~ (banlist | comment | NEWLINE)* ~ EOI }
